### ISSUE TITLE
Timer & Start/Stop time

### ISSUE THREAD

**Issue by seuchato** [ondrej1024/crelay#45]
Hi Ondrej
Nice work all of have done. May I suggest to add a timer and/or a start/stop time?
Greez

**Comment by ondrej1024** [comment]
Hi,
timers have been on my TODO list since the beginning of the project. However I don't really have any use for them anymore. I am controlling my relays from a higher level application like OpenHAB which has all the smart logic and use `crelay` only to pass the on/off commands to the relays.
So I will not implement this timer function myself. But contributions are always welcome and if someone wants to add this feature I will happily accept it :smiley:
